FROM resin/%%RESIN_MACHINE_NAME%%-node:8-slim

WORKDIR /usr/src/app/frontend

COPY package.json package.json

RUN JOBS=MAX npm install --production

COPY . ./

# ENV SERVER_URL="https://f.kth.se", hardcoded in instagramCompiler.js instead.
RUN npm run-script build
RUN npm install -g serve
ENV INITSYSTEM on
CMD ["serve", "--single", "build", "-p", "3000"]
