# SHOULD BE ABSOLUTE PATH (starting with '/')
BASE_PATH = "/BASE/PATH/HERE/kons-screen/APIs/"

FACEBOOK_APP_ID = "FB_APP_ID_HERE"
FACEBOOK_APP_SECRET = "FB_APP_SECRET_HERE"
GOOGLE_API_KEY = "GOOGLE_API_KEY_HERE"