# REPLACE TO ABSOLUTE PATH IF RUNNING OUTSIDE `APIs/`
DB_PATH = "db/"  # (starting with '/')

FACEBOOK_APP_ID = "FB_APP_ID_HERE"
FACEBOOK_APP_SECRET = "FB_APP_SECRET_HERE"
GOOGLE_API_KEY = "GOOGLE_API_KEY_HERE"